### ISSUE TITLE
Duplicação de código do Elastic

### ISSUE THREAD

**Issue by pablodiegoss** [lappis-unb/Bottis#9]
rabbitmq/consumer/elastic_connector.py
bot/tracker_store.py

Esses arquivos tem códigos extremamente duplicados, é necessário verificar a utilidade de cada um para apagar um deles ou melhorar a reutilização entre eles.

**Comment by guilacerda** [comment]
De acordo com o @MatheusMiranda o arquivo no bot/tracker_store não está mais sendo utilizado.
